apiVersion: v1
kind: Pod
metadata:
  name: irsa-proof
  namespace: demo-app
  labels:
    app: irsa-proof
    owner: platform
    env: dev
spec:
  serviceAccountName: irsa-test
  restartPolicy: Never
  containers:
  - name: curl
    image: 910321623036.dkr.ecr.ap-south-1.amazonaws.com/platform/curl:8.5.0
    command: ["sleep", "3600"]
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
